[package]
name = "tunic-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "Tunic"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui-platform.workspace = true
tunic-core.workspace = true
tunic-macos.workspace = true
tunic-ui.workspace = true

[lints]
workspace = true
