[package]
name = "tunic-ffi"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
boltffi = "=0.30.1"
tunic-core.workspace = true
tunic-presets.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
tunic-macos.workspace = true

[lints]
workspace = true
